// Auto-generated. NK Survey Status v2 extraction + full fleet merge.
// Updated: 2026-08-15 21:51 | Ships: 56

const ships = {
  "SUNNY_BEYLA": {
    name: "SUNNY BEYLA",
    imo: "9364320",
    classSociety: "NK",
    flag: "Panama",
    gt: "90092",
    dwt: null,
    buildDate: "29 May 2006",
    surveys: [],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "21 Jan 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "21 Jan 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "21 Jan 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "21 Jan 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "21 Oct 2027", "status": "VALID"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_BOFFA": {
    name: "SUNNY BOFFA",
    imo: "9253090",
    classSociety: "NK",
    flag: "Liberia",
    gt: "87413",
    dwt: null,
    buildDate: "28 Nov 2001",
    surveys: [{"type": "other", "description": "Load Line", "due_date": "27 Nov 2026", "status": "Not Due"}, {"type": "other", "description": "Safety Construction", "due_date": "27 Nov 2026", "status": "Not Due"}, {"type": "other", "description": "Safety Equipment", "due_date": "27 Nov 2026", "status": "Not Due"}, {"type": "other", "description": "Safety Radio", "due_date": "27 Nov 2026", "status": "Not Due"}, {"type": "other", "description": "BWM", "due_date": "19 Nov 2021", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "27 Nov 2026", "status": "Not Due"}, {"type": "other", "description": "DOC", "due_date": "29 Jul 2021", "status": "Not Due"}, {"type": "other", "description": "SMC", "due_date": "07 Jan 2023", "status": "Not Due"}, {"type": "other", "description": "MLC", "due_date": "07 Jan 2023", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "27 Nov 2026", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "27 Nov 2026", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "27 Nov 2026", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "27 Nov 2026", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "19 Nov 2021", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "27 Nov 2026", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "29 Jul 2021", "status": "EXPIRED"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "07 Jan 2023", "status": "EXPIRED"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "07 Jan 2023", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_BOKE": {
    name: "SUNNY BOKE",
    imo: "9198240",
    classSociety: "NK",
    flag: "Panama",
    gt: "87473",
    dwt: null,
    buildDate: "21 Feb 2001",
    surveys: [{"type": "other", "description": "BWM", "due_date": "30 Jun 2025", "status": "Not Due"}, {"type": "other", "description": "DOC", "due_date": "29 Jul 2021", "status": "Not Due"}, {"type": "other", "description": "SMC", "due_date": "28 Oct 2025", "status": "Not Due"}, {"type": "other", "description": "MLC", "due_date": "28 Oct 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "29 Jun 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "29 Jun 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "29 Jun 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "29 Jun 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "30 Jun 2025", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "29 Jun 2030", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "29 Jul 2021", "status": "EXPIRED"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "28 Oct 2025", "status": "EXPIRED"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "28 Oct 2025", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_CONAKRY": {
    name: "SUNNY CONAKRY",
    imo: "9406489",
    classSociety: "NK",
    flag: "Hong Kong",
    gt: "90092",
    dwt: null,
    buildDate: "22 Nov 2007",
    surveys: [{"type": "other", "description": "BWM", "due_date": "26 Nov 2022", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "20 Oct 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "21 Nov 2027", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "21 Nov 2027", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "21 Nov 2027", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "21 Nov 2027", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "26 Nov 2022", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "20 Oct 2025", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_COYAH": {
    name: "SUNNY COYAH",
    imo: "9387114",
    classSociety: "NK",
    flag: "Hong Kong",
    gt: "90125",
    dwt: null,
    buildDate: "26 Apr 2007",
    surveys: [{"type": "other", "description": "BWM", "due_date": "05 May 2022", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "05 May 2022", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_DABOLA": {
    name: "SUNNY DABOLA",
    imo: "9387114",
    classSociety: "NK",
    flag: "Hong Kong",
    gt: "106367",
    dwt: null,
    buildDate: "23 Oct 2009",
    surveys: [{"type": "other", "description": "BWM", "due_date": "05 May 2022", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "05 May 2022", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "25 Apr 2027", "status": "VALID"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_FARANAH": {
    name: "SUNNY FARANAH",
    imo: "",
    classSociety: "CCS",
    flag: "",
    gt: "101933",
    dwt: null,
    buildDate: "2004-11-26",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2025-12-18", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2025-05-01", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2022-08-09", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2027-08-08", "status": "Not Due"}],
    certificates: [{"name": "ISM DOC", "type": "STATUTORY", "expiry_date": "2026-08-05", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "2026-08-15", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2025-12-18", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2025-12-18", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2027-03-01", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-08-05", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-08-05", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-08-05", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-08-05", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-15", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "SUNNY_FRIA": {
    name: "SUNNY FRIA",
    imo: "",
    classSociety: "CCS",
    flag: "",
    gt: "89877",
    dwt: null,
    buildDate: "2004-06-30",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2027-06-03", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2026-07-10", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2024-09-10", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2029-09-09", "status": "Not Due"}],
    certificates: [{"name": "ISM DOC", "type": "STATUTORY", "expiry_date": "2026-07-10", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2027-06-03", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2027-06-03", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2029-06-03", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-07-10", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-07-10", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-07-10", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "2027-06-03", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2029-06-03", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-07-10", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-09", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "SUNNY_KALOUM": {
    name: "SUNNY KALOUM",
    imo: "9336969",
    classSociety: "NK",
    flag: "Panama",
    gt: "106367",
    dwt: null,
    buildDate: "06 Nov 2007",
    surveys: [{"type": "other", "description": "BWM", "due_date": "16 Jul 2025", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "16 Jul 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "07 Oct 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "07 Oct 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "07 Oct 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "07 Oct 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "16 Jul 2025", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "16 Jul 2025", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_KAMSAR": {
    name: "SUNNY KAMSAR",
    imo: "9336957",
    classSociety: "NK",
    flag: "Hong Kong",
    gt: "101953",
    dwt: null,
    buildDate: "25 May 2007",
    surveys: [{"type": "other", "description": "BWM", "due_date": "16 Jul 2025", "status": "Not Due"}, {"type": "other", "description": "DOC", "due_date": "23 Apr 2026", "status": "Not Due"}, {"type": "other", "description": "SMC", "due_date": "15 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "MLC", "due_date": "15 Jun 2026", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "24 Jun 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "24 Jun 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "24 Jun 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "24 Jun 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "16 Jul 2025", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "24 Jun 2030", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "23 Apr 2026", "status": "EXPIRED"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "15 Jun 2026", "status": "EXPIRED"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "15 Jun 2026", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_KEROUANE": {
    name: "SUNNY KEROUANE",
    imo: "9398113",
    classSociety: "NK",
    flag: "Liberia",
    gt: "106367",
    dwt: null,
    buildDate: "25 May 2010",
    surveys: [{"type": "other", "description": "BWM", "due_date": "06 Jun 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "24 May 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "24 May 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "24 May 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "24 May 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "06 Jun 2025", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_KINDIA": {
    name: "SUNNY KINDIA",
    imo: "9374064",
    classSociety: "NK",
    flag: "Hong Kong",
    gt: "90396",
    dwt: null,
    buildDate: "12 Sep 2006",
    surveys: [{"type": "other", "description": "BWM", "due_date": "20 Apr 2024", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "20 Apr 2024", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "01 Jul 2029", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "01 Jul 2029", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "01 Jul 2029", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "01 Jul 2029", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "20 Apr 2024", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "20 Apr 2024", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_KOGON": {
    name: "SUNNY KOGON",
    imo: "",
    classSociety: "CCS",
    flag: "Liberia",
    gt: "106312",
    dwt: null,
    buildDate: "2006-04-17",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2026-09-07", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2026-01-11", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2027-12-06", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2027-11-07", "status": "Not Due"}, {"type": "dry_docking", "description": "Rudder bearing bushes of starlite 11630 to be specially examined at each scheduled drydocking and", "due_date": "", "status": "Not Due"}],
    certificates: [{"name": "ISM DOC", "type": "STATUTORY", "expiry_date": "2026-01-11", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2026-09-07", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2026-09-07", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2027-09-07", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-01-11", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-01-11", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-01-11", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "2026-01-11", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-15", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "SUNNY_LABE": {
    name: "SUNNY LABE",
    imo: "9271597",
    classSociety: "NK",
    flag: "Panama",
    gt: "102101",
    dwt: null,
    buildDate: "09 Nov 2004",
    surveys: [{"type": "other", "description": "BWM", "due_date": "08 Sep 2024", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "08 Sep 2024", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "18 Aug 2029", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "18 Aug 2029", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "18 Aug 2029", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "18 Aug 2029", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "08 Sep 2024", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "08 Sep 2024", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_LINK": {
    name: "SUNNY LINK",
    imo: "9254666",
    classSociety: "NK",
    flag: "Liberia",
    gt: "88674",
    dwt: null,
    buildDate: "26 Jun 2002",
    surveys: [{"type": "other", "description": "BWM", "due_date": "14 Jul 2022", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "25 Jun 2027", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "25 Jun 2027", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "25 Jun 2027", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "25 Jun 2027", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "14 Jul 2022", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "25 Jun 2027", "status": "VALID"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_MAMOU": {
    name: "SUNNY MAMOU",
    imo: "9346342",
    classSociety: "NK",
    flag: "Panama",
    gt: "104725",
    dwt: null,
    buildDate: "07 Oct 2005",
    surveys: [{"type": "other", "description": "BWM", "due_date": "29 Sep 2025", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "29 Sep 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "29 Sep 2025", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "29 Sep 2025", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_MOREBAYA": {
    name: "SUNNY MOREBAYA",
    imo: "9331426",
    classSociety: "NK",
    flag: "Liberia",
    gt: "101953",
    dwt: null,
    buildDate: "15 Nov 2005",
    surveys: [{"type": "other", "description": "BWM", "due_date": "08 Sep 2025", "status": "Not Due"}, {"type": "other", "description": "DOC", "due_date": "29 Jul 2021", "status": "Not Due"}, {"type": "other", "description": "SMC", "due_date": "29 Dec 2025", "status": "Not Due"}, {"type": "other", "description": "MLC", "due_date": "29 Dec 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "14 Nov 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "14 Nov 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "14 Nov 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "14 Nov 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "08 Sep 2025", "status": "EXPIRED"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "29 Jul 2021", "status": "EXPIRED"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "29 Dec 2025", "status": "EXPIRED"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "29 Dec 2025", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_NZKORE": {
    name: "SUNNY NZKORE",
    imo: "9346342",
    classSociety: "NK",
    flag: "Panama",
    gt: "90111",
    dwt: null,
    buildDate: "10 Apr 2009",
    surveys: [{"type": "other", "description": "BWM", "due_date": "29 Sep 2025", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "29 Sep 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "06 Oct 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "29 Sep 2025", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "29 Sep 2025", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_SAILOR": {
    name: "SUNNY SAILOR",
    imo: "9439125",
    classSociety: "NK",
    flag: "Panama",
    gt: "90091",
    dwt: null,
    buildDate: "13 Jun 2008",
    surveys: [{"type": "other", "description": "Load Line", "due_date": "07 Sep 2026", "status": "Not Due"}, {"type": "other", "description": "Safety Construction", "due_date": "07 Sep 2026", "status": "Not Due"}, {"type": "other", "description": "Safety Equipment", "due_date": "07 Sep 2026", "status": "Not Due"}, {"type": "other", "description": "Safety Radio", "due_date": "07 Sep 2026", "status": "Not Due"}, {"type": "other", "description": "BWM", "due_date": "12 Jun 2021", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "12 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "07 Sep 2026", "status": "EXPIRING"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "07 Sep 2026", "status": "EXPIRING"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "07 Sep 2026", "status": "EXPIRING"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "07 Sep 2026", "status": "EXPIRING"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "12 Jun 2021", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "12 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_SIGUIRI": {
    name: "SUNNY SIGUIRI",
    imo: "9406453",
    classSociety: "NK",
    flag: "Panama",
    gt: "104721",
    dwt: null,
    buildDate: "25 Apr 2007",
    surveys: [{"type": "other", "description": "BWM", "due_date": "23 Jul 2022", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "23 Jul 2022", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "23 Jul 2022", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "23 Jul 2022", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "SUNNY_SKY": {
    name: "SUNNY SKY",
    imo: "",
    classSociety: "BV",
    flag: "",
    gt: "94145",
    dwt: null,
    buildDate: "",
    surveys: [{"type": "annual_survey", "description": "Annual survey of structure", "due_date": "", "status": "Not Due"}, {"type": "dry_docking", "description": "Bottom Survey in Dry Dock or afloat", "due_date": "", "status": "Not Due"}, {"type": "tail_shaft", "description": "Centre Tailshaft-Complete Survey", "due_date": "", "status": "Not Due"}, {"type": "special_survey", "description": "Garbage Renewal Survey", "due_date": "", "status": "Not Due"}],
    certificates: [{"name": "ISM SMC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}],
    source: {"class_society": "BV", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "SUNNY_STAR": {
    name: "SUNNY STAR",
    imo: "",
    classSociety: "CCS",
    flag: "Singapore",
    gt: "94175",
    dwt: null,
    buildDate: "2011-06-03",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2027-03-10", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2028-03-10", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2026-06-17", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2031-06-16", "status": "Not Due"}],
    certificates: [{"name": "ISM DOC", "type": "STATUTORY", "expiry_date": "2026-06-17", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2027-02-09", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2027-03-10", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2031-06-09", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-06-17", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-06-17", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-06-17", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2031-06-09", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-06-17", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-09", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_AMBITION": {
    name: "WINNING AMBITION",
    imo: "",
    classSociety: "DNV",
    flag: "Singapore",
    gt: "174863",
    dwt: null,
    buildDate: "2025-10-22",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2027-03-16", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2028-03-16", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2031-03-16", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2036-06-15", "status": "Not Due"}, {"type": "dry_docking", "description": "Statement of Drydock Inspection", "due_date": "2026-06-16", "status": "Not Due"}],
    certificates: [{"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2026-06-16", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-06-16", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-06-16", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-06-16", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2031-03-16", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-06-16", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}],
    source: {"class_society": "DNV", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_ANGEL": {
    name: "WINNING ANGEL",
    imo: "9406506",
    classSociety: "NK",
    flag: "Singapore",
    gt: "104761",
    dwt: null,
    buildDate: "19 Dec 2007",
    surveys: [{"type": "other", "description": "BWM", "due_date": "03 Mar 2023", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "03 Nov 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "18 Dec 2027", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "18 Dec 2027", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "18 Dec 2027", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "18 Dec 2027", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "03 Mar 2023", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "03 Nov 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_BRIGHT": {
    name: "WINNING BRIGHT",
    imo: "9492218",
    classSociety: "NK",
    flag: "Singapore",
    gt: "106884",
    dwt: null,
    buildDate: "04 Jan 2012",
    surveys: [{"type": "other", "description": "BWM", "due_date": "27 Sep 2024", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "27 Sep 2024", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "21 Aug 2029", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "21 Aug 2029", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "21 Aug 2029", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "21 Aug 2029", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "27 Sep 2024", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "27 Sep 2024", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_BROTHER": {
    name: "WINNING BROTHER",
    imo: "9406453",
    classSociety: "NK",
    flag: "Panama",
    gt: "94779",
    dwt: null,
    buildDate: "29 Oct 2002",
    surveys: [{"type": "other", "description": "BWM", "due_date": "23 Jul 2022", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "23 Jul 2022", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "24 Apr 2027", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "23 Jul 2022", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "23 Jul 2022", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_CONFIDENCE": {
    name: "WINNING CONFIDENCE",
    imo: "9325001",
    classSociety: "NK",
    flag: "Singapore",
    gt: "90091",
    dwt: null,
    buildDate: "01 Feb 2005",
    surveys: [{"type": "other", "description": "BWM", "due_date": "28 Dec 2024", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "28 Dec 2024", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "31 Jan 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "31 Jan 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "31 Jan 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "31 Jan 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "28 Dec 2024", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "28 Dec 2024", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_DILIGENCE": {
    name: "WINNING DILIGENCE",
    imo: "9374088",
    classSociety: "NK",
    flag: "Singapore",
    gt: "90091",
    dwt: null,
    buildDate: "17 May 2006",
    surveys: [{"type": "other", "description": "BWM", "due_date": "12 May 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "14 Apr 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "17 May 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "17 May 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "17 May 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "17 May 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "12 May 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "14 Apr 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_ENDURANCE": {
    name: "WINNING ENDURANCE",
    imo: "9232058",
    classSociety: "NK",
    flag: "Singapore",
    gt: "87590",
    dwt: null,
    buildDate: "22 Jan 2001",
    surveys: [{"type": "other", "description": "BWM", "due_date": "16 Jul 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "16 Jul 2025", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_EXCELLENCE": {
    name: "WINNING EXCELLENCE",
    imo: "9232058",
    classSociety: "NK",
    flag: "Singapore",
    gt: "113929",
    dwt: null,
    buildDate: "26 May 2004",
    surveys: [{"type": "other", "description": "BWM", "due_date": "16 Jul 2025", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "16 Jul 2025", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jul 2030", "status": "VALID"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_FAITH": {
    name: "WINNING FAITH",
    imo: "9314076",
    classSociety: "NK",
    flag: "Singapore",
    gt: "90091",
    dwt: null,
    buildDate: "20 Oct 2004",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Oct 2024", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "07 Oct 2024", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Oct 2024", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "07 Oct 2024", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_GRACE": {
    name: "WINNING GRACE",
    imo: "9314076",
    classSociety: "NK",
    flag: "Singapore",
    gt: "107791",
    dwt: null,
    buildDate: "26 Apr 2016",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Oct 2024", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "07 Oct 2024", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Oct 2024", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "07 Oct 2024", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_HOPE": {
    name: "WINNING HOPE",
    imo: "9314076",
    classSociety: "NK",
    flag: "Singapore",
    gt: "107791",
    dwt: null,
    buildDate: "10 Aug 2016",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Oct 2024", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "07 Oct 2024", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "19 Oct 2029", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Oct 2024", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "07 Oct 2024", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_INTEGRITY": {
    name: "WINNING INTEGRITY",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "92758",
    dwt: null,
    buildDate: "21 Mar 2013",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_JOY": {
    name: "WINNING JOY",
    imo: "",
    classSociety: "CCS",
    flag: "Singapore",
    gt: "106884",
    dwt: null,
    buildDate: "2011-09-13",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2026-08-01", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2026-05-02", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2024-08-09", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2029-08-08", "status": "Not Due"}],
    certificates: [{"name": "ISM DOC", "type": "STATUTORY", "expiry_date": "2025-11-04", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2026-08-01", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2026-08-01", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2029-08-01", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2024-08-09", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2024-08-09", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2024-08-09", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2030-07-10", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2024-08-09", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "2024-03-21", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-09", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_KINDNESS": {
    name: "WINNING KINDNESS",
    imo: "09",
    classSociety: "KR",
    flag: "SINGAPORE",
    gt: "",
    dwt: null,
    buildDate: "2004-12-24",
    surveys: [{"type": "tail_shaft", "description": "Propeller Shaft", "due_date": "", "status": "Not Due"}, {"type": "special_survey", "description": "Next Special Survey No.", "due_date": "", "status": "Not Due"}, {"type": "dry_docking", "description": "Kind of Last Docking Survey", "due_date": "", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Intermediate Survey", "due_date": "2028-12-28", "status": "Not Due"}, {"type": "annual_survey", "description": "Annual Survey", "due_date": "2026-12-28", "status": "Not Due"}, {"type": "boiler", "description": "No.1 Aux. Boiler Survey", "due_date": "2028-10-05", "status": "Not Due"}],
    certificates: [{"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2030-09-28", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2030-09-28", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2030-09-28", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "2025-10-05", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2025-10-05", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2025-10-05", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2025-10-05", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "2030-09-28", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2025-10-05", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "2023-07-08", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "2030.09.14", "status": "VALID"}],
    source: {"class_society": "KR", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_LOYALTY": {
    name: "WINNING LOYALTY",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "90091",
    dwt: null,
    buildDate: "09 Aug 2004",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_MISSION": {
    name: "WINNING MISSION",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "92752",
    dwt: null,
    buildDate: "22 Jul 2013",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_NATURE": {
    name: "WINNING NATURE",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "92752",
    dwt: null,
    buildDate: "28 Feb 2014",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_OCEAN": {
    name: "WINNING OCEAN",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "102207",
    dwt: null,
    buildDate: "30 Jun 2003",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_PRIDE": {
    name: "WINNING PRIDE",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "89603",
    dwt: null,
    buildDate: "17 Feb 2009",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_QUEEN": {
    name: "WINNING QUEEN",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "89726",
    dwt: null,
    buildDate: "02 Jun 2006",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_RESILIENCE": {
    name: "WINNING RESILIENCE",
    imo: "9410430",
    classSociety: "CCS",
    flag: "Panama",
    gt: "114026",
    dwt: null,
    buildDate: "2004-12-24",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2026-06-01", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2025-08-05", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2027-08-31", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2027-08-31", "status": "Not Due"}],
    certificates: [{"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2026-06-01", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2026-06-01", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2027-06-01", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-04-25", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-04-25", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-04-25", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2027-06-01", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-04-25", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-09", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_RICH": {
    name: "WINNING RICH",
    imo: "09",
    classSociety: "KR",
    flag: "SINGAPORE",
    gt: "",
    dwt: null,
    buildDate: "2009-11-30",
    surveys: [{"type": "tail_shaft", "description": "Propeller Shaft", "due_date": "", "status": "Not Due"}, {"type": "special_survey", "description": "Next Special Survey No.", "due_date": "", "status": "Not Due"}, {"type": "dry_docking", "description": "Kind of Last Docking Survey", "due_date": "", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Intermediate Survey", "due_date": "2028-02-16", "status": "Not Due"}, {"type": "annual_survey", "description": "Annual Survey", "due_date": "2027-02-16", "status": "Not Due"}, {"type": "boiler", "description": "No.1 Aux. Boiler Survey", "due_date": "2027-09-11", "status": "Not Due"}],
    certificates: [{"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2029-11-16", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2029-11-16", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2029-11-16", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "2024-09-11", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2024-09-11", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2024-09-11", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2024-09-11", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "2029-11-16", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2024-09-11", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "2023-09-15", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "2027.05.03", "status": "VALID"}],
    source: {"class_society": "KR", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_RISING": {
    name: "WINNING RISING",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "90421",
    dwt: null,
    buildDate: "30 Jun 2009",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_SEA": {
    name: "WINNING SEA",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "101953",
    dwt: null,
    buildDate: "24 Mar 2003",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_SPIRIT": {
    name: "WINNING SPIRIT",
    imo: "09",
    classSociety: "KR",
    flag: "SINGAPORE",
    gt: "",
    dwt: null,
    buildDate: "2011-03-28",
    surveys: [{"type": "tail_shaft", "description": "Propeller Shaft", "due_date": "", "status": "Not Due"}, {"type": "special_survey", "description": "Next Special Survey No.", "due_date": "", "status": "Not Due"}, {"type": "dry_docking", "description": "Kind of Last Docking Survey", "due_date": "", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Intermediate Survey", "due_date": "2029-11-11", "status": "Not Due"}, {"type": "annual_survey", "description": "Annual Survey", "due_date": "2027-11-11", "status": "Not Due"}, {"type": "boiler", "description": "No.1 Aux. Boiler Survey", "due_date": "2029-08-03", "status": "Not Due"}],
    certificates: [{"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2031-08-02", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2031-08-11", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2031-08-11", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "2026-08-03", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-08-03", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-08-03", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-08-03", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "2031-08-11", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2031-08-11", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-08-03", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "2024-08-25", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "SMC", "type": "STATUTORY", "expiry_date": "2027.05.14", "status": "VALID"}],
    source: {"class_society": "KR", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_TEAM": {
    name: "WINNING TEAM",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "102319",
    dwt: null,
    buildDate: "30 Mar 2007",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_TIMES": {
    name: "WINNING TIMES",
    imo: "",
    classSociety: "CCS",
    flag: "Singapore",
    gt: "107514",
    dwt: null,
    buildDate: "2014-06-30",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2027-01-17", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2027-01-17", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2030-04-16", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2030-04-16", "status": "Not Due"}],
    certificates: [{"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2027-01-17", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2027-01-17", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2030-01-17", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-06-10", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-06-10", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-06-10", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2030-01-17", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-06-10", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-15", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_UNIVERSE": {
    name: "WINNING UNIVERSE",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "102092",
    dwt: null,
    buildDate: "11 Jan 2006",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_VISION": {
    name: "WINNING VISION",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "107791",
    dwt: null,
    buildDate: "25 Nov 2019",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_WAVE": {
    name: "WINNING WAVE",
    imo: "",
    classSociety: "CCS",
    flag: "Singapore",
    gt: "107222",
    dwt: null,
    buildDate: "2015-05-23",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2026-11-18", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2027-11-18", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2031-02-17", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2031-02-15", "status": "Not Due"}],
    certificates: [{"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2026-11-18", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2026-11-18", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2030-11-18", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2026-06-03", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2026-06-03", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2026-06-03", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2030-11-18", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2026-06-03", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-15", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_WEALTH": {
    name: "WINNING WEALTH",
    imo: "",
    classSociety: "CCS",
    flag: "Singapore",
    gt: "114019",
    dwt: null,
    buildDate: "2004-12-24",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2025-09-09", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2024-12-24", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2026-10-12", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2029-12-23", "status": "Not Due"}],
    certificates: [{"name": "ISM DOC", "type": "STATUTORY", "expiry_date": "2024-12-24", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2025-09-09", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2025-09-09", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2026-07-13", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2024-12-24", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2024-12-24", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2024-12-24", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2026-07-13", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2024-12-24", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "2024-12-24", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-09", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_WISDOM": {
    name: "WINNING WISDOM",
    imo: "",
    classSociety: "CCS",
    flag: "Singapore",
    gt: "108208",
    dwt: null,
    buildDate: "2015-07-31",
    surveys: [{"type": "boiler", "description": "锅炉", "due_date": "", "status": "Not Due"}, {"type": "annual_survey", "description": "Class Annual Survey", "due_date": "2027-07-01", "status": "Not Due"}, {"type": "intermediate_survey", "description": "Class Intermediate Survey", "due_date": "2027-04-02", "status": "Not Due"}, {"type": "special_survey", "description": "Class Special Survey for", "due_date": "2025-06-15", "status": "Not Due"}, {"type": "tail_shaft", "description": "尾轴检验", "due_date": "2030-07-01", "status": "Not Due"}],
    certificates: [{"name": "ISM DOC", "type": "STATUTORY", "expiry_date": "2024-10-05", "status": "VALID"}, {"name": "ISPS", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "MLC", "type": "STATUTORY", "expiry_date": "2024-10-05", "status": "VALID"}, {"name": "IOPP", "type": "STATUTORY", "expiry_date": "2027-07-01", "status": "VALID"}, {"name": "IAPP", "type": "STATUTORY", "expiry_date": "2027-07-01", "status": "VALID"}, {"name": "ISPP", "type": "STATUTORY", "expiry_date": "2030-07-01", "status": "VALID"}, {"name": "Load Line", "type": "STATUTORY", "expiry_date": "", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "2025-06-15", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "2025-06-15", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "2025-06-15", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "2027-07-01", "status": "VALID"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "2030-07-01", "status": "VALID"}, {"name": "Cargo Gear", "type": "STATUTORY", "expiry_date": "2025-06-15", "status": "VALID"}, {"name": "AFS", "type": "STATUTORY", "expiry_date": "2024-10-05", "status": "VALID"}, {"name": "DOC", "type": "STATUTORY", "expiry_date": "2026-08-09", "status": "VALID"}],
    source: {"class_society": "CCS", "report_date": "2026-08-15", "extraction_method": "pdf_text", "confidence": "medium"},
  },
  "WINNING_WORLD": {
    name: "WINNING WORLD",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "107786",
    dwt: null,
    buildDate: "03 Jan 2020",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
  "WINNING_YOUTH": {
    name: "WINNING YOUTH",
    imo: "9722950",
    classSociety: "NK",
    flag: "Singapore",
    gt: "101933",
    dwt: null,
    buildDate: "01 Jul 2005",
    surveys: [{"type": "other", "description": "BWM", "due_date": "07 Jun 2026", "status": "Not Due"}, {"type": "other", "description": "IHM", "due_date": "15 Jun 2021", "status": "Not Due"}],
    certificates: [{"name": "Load Line", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Construction", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Equipment", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "Safety Radio", "type": "STATUTORY", "expiry_date": "09 Aug 2031", "status": "VALID"}, {"name": "BWM", "type": "STATUTORY", "expiry_date": "07 Jun 2026", "status": "EXPIRED"}, {"name": "IHM", "type": "STATUTORY", "expiry_date": "15 Jun 2021", "status": "EXPIRED"}],
    source: {"class_society": "NK", "report_date": "2026-08-15", "extraction_method": "pdf_text+particulars", "confidence": "high", "particulars_source": "NK_Survey_Status_PDF"},
  },
};

module.exports = {
  ships,
  lastUpdated: "2026-08-15 21:51",
  totalShips: 56,
};